import { render, screen, fireEvent, waitFor } from '@testing-library/react-native';
import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { CompetitionsScreen } from '../screens/CompetitionsScreen';
import { CalendarScreen } from '../screens/CalendarScreen';
import { HeaderActions } from '../components/HeaderActions';
import { competitionService } from '../services/competitionService';
import { cupService } from '../services/cupService';
import { statisticsService } from '../services/statisticsService';
import { calendarService } from '../services/calendarService';
import { useCalendarStore } from '../stores/calendarStore';
import { RootStackParamList } from '../navigation/types';
jest.mock('../components/MailboxButton', () => ({ MailboxButton: ({ open }: { open: () => void }) => { const { ActionButton } = jest.requireActual('../components/GameUI'); return <ActionButton title="Correio" onPress={open} />; } }));
jest.mock('../stores/clubStore', () => ({ useClubStore: (select: (state: { data: { club: { id: string } } }) => unknown) => select({ data: { club: { id: 'club' } } }) }));
jest.mock('../services/competitionService', () => ({ competitionService: { get: jest.fn(), matches: jest.fn() } }));
jest.mock('../services/cupService', () => ({ cupService: { get: jest.fn() } }));
jest.mock('../services/statisticsService', () => ({ statisticsService: { competition: jest.fn() } }));
jest.mock('../services/calendarService', () => ({ calendarService: { get: jest.fn() } }));
beforeEach(() => { jest.clearAllMocks(); useCalendarStore.getState().reset(); });
test('championship owns table, games, reports and cup rankings', async () => {
  jest.mocked(competitionService.get).mockResolvedValue({ season: { number: 1, starts_at: '', ends_at: '' }, division: { name: 'A' }, standings: [{ id: 'row', club_id: 'club', club_name: 'Aurora', position: 1, points: 3, games: 1, wins: 1, draws: 0, losses: 0, goals_for: 2, goals_against: 0, goal_difference: 2 }] });
  jest.mocked(competitionService.matches).mockResolvedValue([{ id: 'match', date: '2026-10-15T18:00:00Z', round: 1, status: 'completed', home_name: 'Aurora', away_name: 'Estrela', home_goals: 2, away_goals: 0 }]);
  jest.mocked(cupService.get).mockResolvedValue({ competition: { id: 'cup', name: 'Copa Nacional', status: 'active' }, entry: { status: 'active', phase: 'Semifinal' }, matches: [] });
  jest.mocked(statisticsService.competition).mockResolvedValue({ season: null, ranking: 'goals', rows: [] });
  const navigate = jest.fn();
  await render(<CompetitionsScreen {...({ navigation: { navigate } } as unknown as NativeStackScreenProps<RootStackParamList, 'Competitions'>)} />);
  await screen.findByText('1. Aurora');
  await fireEvent.press(screen.getByText('Ver relatório'));
  expect(navigate).toHaveBeenCalledWith('MatchReport', { id: 'match' });
  await fireEvent.press(screen.getByText('Copa Nacional'));
  await screen.findByText('Semifinal · Em disputa');
  await waitFor(() => expect(statisticsService.competition).toHaveBeenCalledWith('cup', 'goals'));
});
test('calendar selects event day and loads adjacent month without filters', async () => {
  const now = new Date();
  const eventDate = new Date(now.getFullYear(), now.getMonth(), 15, 15);
  jest.mocked(calendarService.get).mockResolvedValue([{ id: 'event', title: 'Aurora × Estrela', type: 'league_match', date: eventDate.toISOString() }]);
  await render(<CalendarScreen />);
  await fireEvent.press(await screen.findByLabelText('Dia 15, com eventos'));
  expect(screen.getByText('Aurora × Estrela')).toBeTruthy();
  expect(screen.queryByText('Aplicar filtros')).toBeNull();
  await fireEvent.press(screen.getByLabelText('Próximo mês'));
  await waitFor(() => expect(calendarService.get).toHaveBeenLastCalledWith({ start: new Date(now.getFullYear(), now.getMonth() + 1, 1).toISOString(), end: new Date(now.getFullYear(), now.getMonth() + 2, 1).toISOString() }));
});
test('header only opens inbox', async () => {
  const openInbox = jest.fn();
  await render(<HeaderActions focused={() => true} openInbox={openInbox} />);
  expect(screen.queryByLabelText('Configurações')).toBeNull();
  await fireEvent.press(screen.getByText('Correio'));
  expect(openInbox).toHaveBeenCalledTimes(1);
});
