"""Reusable name combinations for generated clubs and players."""

FIRST_NAMES = (
    "João",
    "Pedro",
    "Lucas",
    "André",
    "Rafael",
    "Bruno",
    "Caio",
    "Gabriel",
    "Mateus",
    "Thiago",
    "Gustavo",
    "Felipe",
    "Henrique",
    "Daniel",
    "Diego",
    "Vinícius",
    "Eduardo",
    "Leonardo",
    "Arthur",
    "Samuel",
    "Nicolas",
    "Davi",
    "Rodrigo",
    "Leandro",
    "Marcos",
    "Victor",
    "Alex",
    "Fernando",
    "Igor",
    "Renato",
)
SURNAMES = (
    "Silva",
    "Santos",
    "Costa",
    "Souza",
    "Lima",
    "Alves",
    "Oliveira",
    "Pereira",
    "Ferreira",
    "Rodrigues",
    "Carvalho",
    "Gomes",
    "Martins",
    "Rocha",
    "Ribeiro",
    "Barbosa",
    "Mendes",
    "Nunes",
    "Teixeira",
    "Azevedo",
    "Moreira",
    "Cardoso",
    "Moura",
    "Castro",
    "Dias",
    "Freitas",
    "Correia",
    "Machado",
    "Vieira",
    "Batista",
)
CLUB_PREFIXES = (
    "Atlético",
    "Esportivo",
    "União",
    "Real",
    "Nacional",
    "Estrela",
    "Grêmio",
    "Juventude",
    "Ferroviário",
    "Racing",
    "Cruzeiro",
    "Sporting",
    "Independente",
    "Olimpique",
    "Vitória",
    "Imperial",
    "Guarani",
    "Fortaleza",
    "Operário",
    "Aurora",
)
CLUB_SUFFIXES = (
    "do Vale",
    "da Serra",
    "do Norte",
    "do Sul",
    "de Santa Luzia",
    "de Monte Alto",
    "de Vila Nova",
    "do Litoral",
    "de Porto Azul",
    "de Bela Vista",
    "de Rio Claro",
    "de Campo Verde",
    "de Nova Esperança",
    "de Santa Cruz",
    "de São Miguel",
    "de Horizonte",
    "de Ponta Nova",
    "da Capital",
    "de Boa Vista",
    "de Lagoa Dourada",
)


def club_name(rng):
    return f"{rng.choice(CLUB_PREFIXES)} {rng.choice(CLUB_SUFFIXES)}"
