version: 2
updates:
  - package-ecosystem: npm
    directory: /mobile
    open-pull-requests-limit: 0
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /backend
    open-pull-requests-limit: 0
    schedule:
      interval: weekly
