import { useEffect, useState } from 'react';
import { Button, Text, View } from 'react-native';
import { useMarketStore } from '../stores/marketStore';
import { marketService } from '../services/marketService';
import { Field, GamePage, cents, money, useAction } from '../components/GameUI';
export function TransferOffersScreen() {
  const store = useMarketStore(), action = useAction();
  const load = store.load;
  const [counter, setCounter] = useState<Record<string, string>>({});
  useEffect(() => { void load(); }, [load]);
  return <GamePage loading={store.loading || action.busy} error={action.error || store.error}><Button title="Atualizar propostas" onPress={() => void store.load()} /><Text>Propostas recebidas</Text>{store.data?.incoming.map(o => <View key={o.id}><Text>{o.id} · {money(o.amount)} · {o.status}{o.salary_offer ? ` · salário ${money(o.salary_offer)} · ${o.contract_months} meses` : ''}</Text>{o.status === 'pending' && <><Button title="Aceitar proposta" disabled={action.busy} onPress={() => void action.run(async () => { if (o.negotiation_version === 2) await marketService.action(o.id, 'accept'); else await marketService.accept(o.id); await store.load(); })} /><Button title="Recusar proposta" disabled={action.busy} onPress={() => void action.run(async () => { if (o.negotiation_version === 2) await marketService.action(o.id, 'reject'); else await marketService.cancelOffer(o.id); await store.load(); })} />{o.negotiation_version === 2 && <><Field label="Contraproposta (R$)" value={counter[o.id] ?? ''} onChange={value => setCounter(current => ({ ...current, [o.id]: value }))} numeric /><Button title="Enviar contraproposta" disabled={action.busy} onPress={() => void action.run(async () => { await marketService.counter(o.id, cents(counter[o.id] ?? '')); await store.load(); })} /></>}</>}</View>)}<Text>Propostas enviadas</Text>{store.data?.outgoing.map(o => <View key={o.id}><Text>{o.id} · {money(o.amount)} · {o.status}{o.salary_offer ? ` · salário ${money(o.salary_offer)} · ${o.contract_months} meses` : ''}</Text>{o.player_decision && <Text>{o.player_decision.reason}</Text>}{o.status === 'counter_offer' && <Button title="Aceitar contraproposta" disabled={action.busy} onPress={() => void action.run(async () => { await marketService.action(o.id, 'accept_counter'); await store.load(); })} />}{o.status === 'player_accepted' && <Button title="Confirmar transferência" disabled={action.busy} onPress={() => void action.run(async () => { await marketService.action(o.id, 'confirm'); await store.load(); })} />}{['pending', 'counter_offer', 'player_accepted'].includes(o.status) && <Button title="Cancelar proposta" disabled={action.busy} onPress={() => void action.run(async () => { await marketService.cancelOffer(o.id); await store.load(); })} />}</View>)}</GamePage>;
}
